# fileName: wrangler.toml
name = "gotrip" # Ganti dengan nama unik proyek Pages Anda di Cloudflare
compatibility_date = "2025-06-17" # Pertahankan tanggal hari ini

[observability.logs]
enabled = true