name = "gotrip" # Pastikan ini unik, misalnya "gotrip-app" atau "gotrip-project"
compatibility_date = "2025-06-17" # Pertahankan tanggal terbaru

# Konfigurasi untuk aset statis (penting untuk Next.js di Pages)
# Gunakan bagian [assets] seperti yang disarankan oleh error log Wrangler
[assets]
# Next.js menghasilkan output ke direktori `.next`
# Namun, jika Anda menggunakan `output: 'export'` di next.config.js,
# maka ini harus menjadi `out`
directory = ".next" # Asumsi umum untuk Next.js Pages

# Bagian observasi log Anda baik-baik saja
[observability.logs]
enabled = true

# Hapus atau komentar bagian [pages_build_output] karena menyebabkan konflik/tidak dikenali
# [pages_build_output]
# directory = "out"