export const currencyContent = [
  { id: 1, currency: 'USD', language: 'en-us', symbol: '$', name: 'US Dollar', flagLink: 'https://flagcdn.com/us.svg' },
  { id: 2, currency: 'EUR', language: 'de-de', symbol: '€', name: 'Euro', flagLink: 'https://flagcdn.com/de.svg' },
  { id: 3, currency: 'GBP', language: 'en-gb', symbol: '£', name: 'Pound Sterling', flagLink: 'https://flagcdn.com/gb.svg' },
  { id: 4, currency: 'PLN', language: 'pl-pl', symbol: 'zł', name: 'Polish Zloty', flagLink: 'https://flagcdn.com/pl.svg' },
  { id: 5, currency: 'BGN', language: 'bg-bg', symbol: 'лв.', name: 'Bulgarian Lev', flagLink: 'https://flagcdn.com/bg.svg' },
  { id: 6, currency: 'THB', language: 'th-th', symbol: '฿', name: 'Thai Baht', flagLink: 'https://flagcdn.com/th.svg' },
  { id: 7, currency: 'AUD', language: 'en-au', symbol: 'A$', name: 'Australian Dollar', flagLink: 'https://flagcdn.com/au.svg' },
  { id: 8, currency: 'HKD', language: 'zh-hk', symbol: 'HK$', name: 'Hong Kong Dollar', flagLink: 'https://flagcdn.com/hk.svg' },
  { id: 9, currency: 'CAD', language: 'en-ca', symbol: 'CA$', name: 'Canadian Dollar', flagLink: 'https://flagcdn.com/ca.svg' },
  { id: 10, currency: 'NZD', language: 'en-nz', symbol: 'NZ$', name: 'New Zealand Dollar', flagLink: 'https://flagcdn.com/nz.svg' },
  { id: 11, currency: 'SGD', language: 'en-sg', symbol: 'S$', name: 'Singapore Dollar', flagLink: 'https://flagcdn.com/sg.svg' },
  { id: 13, currency: 'UAH', language: 'uk-ua', symbol: '₴', name: 'Ukrainian Hryvnia', flagLink: 'https://flagcdn.com/uk.svg' },
  { id: 14, currency: 'CZK', language: 'cs-cz', symbol: 'Kč', name: 'Czech Koruna', flagLink: 'https://flagcdn.com/cz.svg' },
  { id: 15, currency: 'DKK', language: 'da-dk', symbol: 'kr', name: 'Danish Krone', flagLink: 'https://flagcdn.com/da.svg' },
  { id: 16, currency: 'NOK', language: 'no-no', symbol: 'kr', name: 'Norwegian Krone', flagLink: 'https://flagcdn.com/no.svg' },
  { id: 17, currency: 'SEK', language: 'sv-se', symbol: 'kr', name: 'Swedish Krona', flagLink: 'https://flagcdn.com/se.svg' },
  { id: 18, currency: 'RON', language: 'ro-ro', symbol: 'L', name: 'Romanian Leu', flagLink: 'https://flagcdn.com/ro.svg' },
  { id: 19, currency: 'TRY', language: 'tr-tr', symbol: '₺', name: 'Turkish Lira', flagLink: 'https://flagcdn.com/tr.svg' },
  { id: 21, currency: 'BRL', language: 'pt-br', symbol: 'R$', name: 'Brazilian Real', flagLink: 'https://flagcdn.com/br.svg' },
  { id: 22, currency: 'MYR', language: 'ms-my', symbol: 'RM', name: 'Malaysian Ringgit', flagLink: 'https://flagcdn.com/my.svg' },
  { id: 24, currency: 'RUB', language: 'ru-ru', symbol: '₽', name: 'Russian Ruble', flagLink: 'https://flagcdn.com/ru.svg' },
  { id: 25, currency: 'IDR', language: 'id-id', symbol: 'Rp', name: 'Indonesian Rupiah', flagLink: 'https://flagcdn.com/id.svg' },
  { id: 26, currency: 'ILS', language: 'he-il', symbol: '₪', name: 'Israeli Shekel', flagLink: 'https://flagcdn.com/il.svg' },
  { id: 27, currency: 'KRW', language: 'ko-kr', symbol: '₩', name: 'South Korean Won', flagLink: 'https://flagcdn.com/kr.svg' },
  { id: 28, currency: 'JPY', language: 'ja-jp', symbol: '¥', name: 'Japanese Yen', flagLink: 'https://flagcdn.com/jp.svg' },
  { id: 29, currency: 'CNY', language: 'zh-cn', symbol: '¥', name: 'Chinese Yuan', flagLink: 'https://flagcdn.com/cn.svg' },
  { id: 30, currency: 'EUR', language: 'es-es', symbol: '€', name: 'Spanish Euro', flagLink: 'https://flagcdn.com/es.svg' },
  { id: 31, currency: 'EUR', language: 'fr-fr', symbol: '€', name: 'French Euro', flagLink: 'https://flagcdn.com/fr.svg' },
  { id: 32, currency: 'EUR', language: 'it-it', symbol: '€', name: 'Italian Euro', flagLink: 'https://flagcdn.com/it.svg' },
  { id: 33, currency: 'EUR', language: 'nl-nl', symbol: '€', name: 'Dutch Euro', flagLink: 'https://flagcdn.com/nl.svg' },
  { id: 34, currency: 'INR', language: 'en-in', symbol: '₹', name: 'Indian Rupee', flagLink: 'https://flagcdn.com/in.svg' },
  { id: 35, currency: 'MXN', language: 'es-mx', symbol: '$', name: 'Mexican Peso', flagLink: 'https://flagcdn.com/mx.svg' },
  { id: 36, currency: 'SAR', language: 'ar-sa', symbol: '﷼', name: 'Saudi Riyal', flagLink: 'https://flagcdn.com/sa.svg' },
  { id: 37, currency: 'CHF', language: 'de-ch', symbol: 'CHF', name: 'Swiss Franc', flagLink: 'https://flagcdn.com/ch.svg' },
  { id: 38, currency: 'ZAR', language: 'en-za', symbol: 'R', name: 'South African Rand', flagLink: 'https://flagcdn.com/za.svg' },
  { id: 40, currency: 'EGP', language: 'ar-eg', symbol: '£', name: 'Egyptian Pound', flagLink: 'https://flagcdn.com/eg.svg' },
];

export const defaultCurrency = 'USD';
export const defaultCurrencySlug = 'usd';
export const defaultCurrencyLocale = 'en-us';